### ISSUE TITLE
test rest/http

### ISSUE THREAD

**Issue by trevor-atlas** [trevor-atlas/vor#20]
example way to return generic json/text:
```
[]byte(`
Hacker: true
name: steve
hobbies:
- skateboarding
- snowboarding
- go
clothing:
  jacket: leather
  trousers: denim
age: 35
eyes : brown
beard: true
`)
```
